# Python, Numpy and Matplotlab Assignment


## Problem 1: Second largest element


In [1]:
def second_largest(lst):
    if len(lst) < 2:
        return None
    largest = float('-inf')
    second = float('-inf')
    for num in lst:
        if num > largest:
            second = largest
            largest = num
        elif num > second and num != largest:
            second = num
    return second if second != float('-inf') else None

nums = [10, 20, 4, 45, 99, 99]
print(f'List: {nums}')
print(f'Second largest: {second_largest(nums)}')


List: [10, 20, 4, 45, 99, 99]
Second largest: 45


## Problem 2: Frequency of each character


In [2]:
def count_frequency(s):
    freq = {}
    for char in s:
        freq[char] = freq.get(char, 0) + 1
    return freq

text = 'hello world'
print(f"String: '{text}'")
print(f"Frequency: {count_frequency(text)}")


String: 'hello world'
Frequency: {'h': 1, 'e': 1, 'l': 3, 'o': 2, ' ': 1, 'w': 1, 'r': 1, 'd': 1}


## Problem 3: Common elements without set


In [3]:
def find_common(list1, list2):
    common = []
    for item in list1:
        if item in list2 and item not in common:
            common.append(item)
    return common

l1 = [1, 2, 3, 4, 5]
l2 = [4, 5, 6, 7, 8]
print(f"List 1: {l1}")
print(f"List 2: {l2}")
print(f"Common elements: {find_common(l1, l2)}")


List 1: [1, 2, 3, 4, 5]
List 2: [4, 5, 6, 7, 8]
Common elements: [4, 5]


## Problem 4: Armstrong Number


In [4]:
def is_armstrong(n):
    num_str = str(n)
    power = len(num_str)
    total = sum(int(digit) ** power for digit in num_str)
    return total == n

num = 153
print(f"Is {num} an Armstrong number? {is_armstrong(num)}")


Is 153 an Armstrong number? True


## Problem 5: Sort tuples by marks


In [5]:
def sort_by_marks(students):
    return sorted(students, key=lambda x: x[1])

data = [('Alice', 85), ('Bob', 92), ('Charlie', 78)]
print(f"Original: {data}")
print(f"Sorted: {sort_by_marks(data)}")


Original: [('Alice', 85), ('Bob', 92), ('Charlie', 78)]
Sorted: [('Charlie', 78), ('Alice', 85), ('Bob', 92)]


## Problem 6: First non-repeating character


In [6]:
def first_non_repeating(s):
    freq = {}
    for char in s:
        freq[char] = freq.get(char, 0) + 1
    for char in s:
        if freq[char] == 1:
            return char
    return None

text = 'swiss'
print(f"String: '{text}'")
print(f"First non-repeating character: {first_non_repeating(text)}")


String: 'swiss'
First non-repeating character: w


## Problem 7: Remove duplicates maintaining order


In [7]:
def remove_duplicates(lst):
    result = []
    seen = set()
    for item in lst:
        if item not in seen:
            seen.add(item)
            result.append(item)
    return result

nums = [1, 2, 2, 3, 4, 4, 5]
print(f"Original: {nums}")
print(f"Without duplicates: {remove_duplicates(nums)}")


Original: [1, 2, 2, 3, 4, 4, 5]
Without duplicates: [1, 2, 3, 4, 5]


## Problem 8: Swap keys and values


In [8]:
def swap_dict(d):
    return {v: k for k, v in d.items()}

my_dict = {'a': 1, 'b': 2, 'c': 3}
print(f"Original: {my_dict}")
print(f"Swapped: {swap_dict(my_dict)}")


Original: {'a': 1, 'b': 2, 'c': 3}
Swapped: {1: 'a', 2: 'b', 3: 'c'}


## Problem 9: Find target sum pairs


In [9]:
def find_pairs(lst, target):
    pairs = []
    seen = set()
    for num in lst:
        complement = target - num
        if complement in seen:
            pairs.append((complement, num))
        seen.add(num)
    return pairs

nums = [1, 5, 7, -1, 5]
target_sum = 6
print(f"List: {nums}, Target: {target_sum}")
print(f"Pairs: {find_pairs(nums, target_sum)}")


List: [1, 5, 7, -1, 5], Target: 6
Pairs: [(1, 5), (7, -1), (1, 5)]


## Problem 10: Flatten nested list


In [10]:
def flatten_list(nested):
    flat = []
    for item in nested:
        if isinstance(item, list):
            flat.extend(flatten_list(item))
        else:
            flat.append(item)
    return flat

nested_data = [1, [2, [3, 4], 5], 6]
print(f"Nested: {nested_data}")
print(f"Flattened: {flatten_list(nested_data)}")


Nested: [1, [2, [3, 4], 5], 6]
Flattened: [1, 2, 3, 4, 5, 6]


## Problem 11: Find mean, median, and std dev


In [11]:
import numpy as np
arr = np.array([12, 45, 67, 89, 34, 23])
print(f"Array: {arr}")
print(f"Mean: {np.mean(arr)}")
print(f"Median: {np.median(arr)}")
print(f"Standard Deviation: {np.std(arr)}")


Array: [12 45 67 89 34 23]
Mean: 45.0
Median: 39.5
Standard Deviation: 26.68332812825184


## Problem 12: Multiply two arrays


In [12]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 * arr2
print(f"Array 1: {arr1}")
print(f"Array 2: {arr2}")
print(f"Resultant array: {result}")


Array 1: [1 2 3]
Array 2: [4 5 6]
Resultant array: [ 4 10 18]


## Problem 13: Transpose a 2D matrix


In [13]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6]])
transposed = np.transpose(matrix)
print("Original Matrix:\n", matrix)
print("Transposed Matrix:\n", transposed)


Original Matrix:
 [[1 2 3]
 [4 5 6]]
Transposed Matrix:
 [[1 4]
 [2 5]
 [3 6]]


## Problem 14: Replace all odd numbers with -1


In [14]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
modified = np.where(arr % 2 != 0, -1, arr)
print(f"Original: {arr}")
print(f"Modified: {modified}")


Original: [1 2 3 4 5 6 7]
Modified: [-1  2 -1  4 -1  6 -1]


## Problem 15: Extract diagonal elements


In [15]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
diagonal = np.diag(matrix)
print("Matrix:\n", matrix)
print("Diagonal elements:", diagonal)


Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Diagonal elements: [1 5 9]


## Problem 16: Normalize values


In [16]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print(f"Original: {arr}")
print(f"Normalized: {normalized}")


Original: [10 20 30 40 50]
Normalized: [0.   0.25 0.5  0.75 1.  ]


## Problem 17: Matrix multiplication


In [17]:
import numpy as np
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
result = np.dot(mat1, mat2)
print("Matrix 1:\n", mat1)
print("Matrix 2:\n", mat2)
print("Result:\n", result)


Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[5 6]
 [7 8]]
Result:
 [[19 22]
 [43 50]]


## Problem 18: Find indices > value


In [18]:
import numpy as np
arr = np.array([10, 50, 30, 70, 20, 90])
value = 40
indices = np.where(arr > value)[0]
print(f"Array: {arr}, Value: {value}")
print(f"Indices: {indices}")


Array: [10 50 30 70 20 90], Value: 40
Indices: [1 3 5]


## Matplotlib Problems (Requires Execution within an Environment)


In [19]:
import matplotlib.pyplot as plt
x = [1, 2, 3, 4, 5]
y = [10, 25, 15, 30, 20]
plt.plot(x, y, marker="o")
plt.title("Line Plot")
plt.xlabel("X values")
plt.ylabel("Y values")
plt.show()


<Line plot would be rendered here on execution>


In [20]:
import matplotlib.pyplot as plt
products = ["A", "B", "C", "D", "E"]
sales = [150, 200, 300, 250, 100]
plt.bar(products, sales, color="skyblue")
plt.title("Product Sales")
plt.xlabel("Products")
plt.ylabel("Sales")
plt.show()


<Bar chart would be rendered here on execution>


In [21]:
import matplotlib.pyplot as plt
categories = ["Rent", "Food", "Transport", "Utilities", "Taxes"]
amounts = [30, 25, 10, 15, 20]
plt.pie(amounts, labels=categories, autopct="%1.1f%%", startangle=90)
plt.title("Expenses Percentage Distribution")
plt.show()


<Pie chart would be rendered here on execution>


In [22]:
import numpy as np
import matplotlib.pyplot as plt
data = np.random.randn(1000)
plt.hist(data, bins=30, color="purple", alpha=0.7)
plt.title("Histogram of Random Dataset")
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.show()


<Histogram chart would be rendered here on execution>


In [23]:
import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(0, 10, 100)
y1 = np.sin(x)
y2 = np.cos(x)
plt.plot(x, y1, label="Sin(x)")
plt.plot(x, y2, label="Cos(x)")
plt.title("Sin and Cos Waves")
plt.legend()
plt.show()


<Dual dataset line chart with legend would be rendered here on execution>


In [24]:
import matplotlib.pyplot as plt
import numpy as np
x = np.random.rand(50) * 10
y = np.random.rand(50) * 10
max_idx = np.argmax(y)
plt.scatter(x, y, color="blue", label="Data points")
plt.scatter(x[max_idx], y[max_idx], color="red", s=100, label="Maximum Point", edgecolor="black")
plt.title("Scatter Plot with Maximum Point")
plt.legend()
plt.show()


<Scatter plot with maximum point highlighted would be rendered here on execution>


In [25]:
import matplotlib.pyplot as plt
months = ["Jan", "Feb", "Mar", "Apr", "May"]
revenue = [1000, 1200, 1500, 1300, 1600]
plt.plot(months, revenue, marker="s", linestyle="--", color="green", linewidth=2)
plt.title("Monthly Revenue", fontsize=14, fontweight="bold")
plt.xlabel("Months", fontsize=12)
plt.ylabel("Revenue ($)", fontsize=12)
plt.grid(True, linestyle=":", alpha=0.6)
plt.show()


<Customized styling plot would be rendered here on execution>
